//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public Nullable<int> AuditNo { get; set; }
        public string ListOfAuditObjection { get; set; }
        public string ActionsTaken { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
