//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class BND
    {
        public int BNDID { get; set; }
        public string ChildName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string PlaceOfBirth { get; set; }
        public string PlaceOfBirthHouse { get; set; }
        public string NameOfMother { get; set; }
        public Nullable<int> UIDmother { get; set; }
        public string NameOfFather { get; set; }
        public Nullable<int> UIDfather { get; set; }
        public string GrandFather { get; set; }
        public string GrandMother { get; set; }
        public string AddressParentsBirth { get; set; }
        public string PermAddress { get; set; }
        public string InformantsName { get; set; }
        public string InformantAddress { get; set; }
        public string NameOfTown { get; set; }
        public Nullable<bool> TownOrVillage { get; set; }
        public string NameOfDistrict { get; set; }
        public string NameOfState { get; set; }
        public string ReligionOfFamily { get; set; }
        public string AnyOtherReligion { get; set; }
        public string FEduc { get; set; }
        public string MEduc { get; set; }
        public string FOccup { get; set; }
        public string MOccup { get; set; }
        public Nullable<int> AgeOfMotherMarraige { get; set; }
        public Nullable<int> AgeOfMotherBirth { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public string AttentionType { get; set; }
        public string DeliveryMethod { get; set; }
        public Nullable<int> BirthWeight { get; set; }
        public string DurationOfPregnancy { get; set; }
        public string UserID { get; set; }
        public Nullable<int> WEBstatusID { get; set; }
        public Nullable<int> RegisterTypeID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
        public virtual WEBstatu WEBstatu { get; set; }
    }
}
