//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetID { get; set; }
        public Nullable<int> BudgtFY { get; set; }
        public int SubLedgerID { get; set; }
        public decimal BudgetAmount { get; set; }
        public decimal ActualAmount { get; set; }
        public decimal OpeningBalance { get; set; }
    
        public virtual SubLedger SubLedger { get; set; }
    }
}
