//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashInHandReg
    {
        public int CashInHandRegID { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public string NameAndDesg { get; set; }
        public Nullable<decimal> CashToDeclareStart { get; set; }
        public string DetailsOfCashExp { get; set; }
        public Nullable<decimal> CashToDeclareEnd { get; set; }
        public string Remarks { get; set; }
    }
}
