//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBRunning
    {
        public System.DateTime EntryDate { get; set; }
        public Nullable<decimal> TotalInflow { get; set; }
        public Nullable<decimal> TotalOutflow { get; set; }
        public Nullable<decimal> CBTotal { get; set; }
    }
}
