//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertSupportDoc
    {
        public int CertSupportDocsID { get; set; }
        public Nullable<int> CertificateRequirementID { get; set; }
        public Nullable<int> RegisterTypeID { get; set; }
        public Nullable<int> CertificateID { get; set; }
        public string DocumentName { get; set; }
    }
}
