//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterCertificate
    {
        public int CharacterID { get; set; }
        public string PersonName { get; set; }
        public string Place { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Village { get; set; }
        public string Address { get; set; }
        public string WardOf { get; set; }
        public Nullable<int> KnownYears { get; set; }
        public string PurposeOf { get; set; }
        public string UserID { get; set; }
        public Nullable<int> WEBstatusID { get; set; }
        public Nullable<int> RegisterTypeID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
        public virtual WEBstatu WEBstatu { get; set; }
    }
}
