//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correction
    {
        public int CorrectionID { get; set; }
        public Nullable<System.DateTime> CorrectionDate { get; set; }
        public Nullable<int> RecieptID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remark { get; set; }
    
        public virtual Form4 Form4 { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
