//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeathCorrCertificate
    {
        public int DeathCorrCertificateID { get; set; }
        public string BirthDeathName { get; set; }
        public string FromName { get; set; }
        public string FromAddress { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string BirthOf { get; set; }
        public Nullable<System.DateTime> BornOn { get; set; }
        public string BirthPlace { get; set; }
        public string FromWrongName { get; set; }
        public string InsteadFWN { get; set; }
        public string NameOfFather { get; set; }
        public string InsteadNF { get; set; }
        public string NameOfMother { get; set; }
        public string InsteadNM { get; set; }
        public string NameOfGrandMother { get; set; }
        public string InsteadNGM { get; set; }
        public string NameOfGrandFather { get; set; }
        public string InsteadNGF { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RegisterTypeID { get; set; }
        public Nullable<int> WEBstatusID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
        public virtual WEBstatu WEBstatu { get; set; }
    }
}
