//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandPeriod
    {
        public int DDID { get; set; }
        public int PeriodID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> SysAmt { get; set; }
    
        public virtual DemandDetail DemandDetail { get; set; }
        public virtual Period Period { get; set; }
    }
}
