//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandYear
    {
        public int DemandYear1 { get; set; }
        public int DDID { get; set; }
        public int PeriodID { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public Nullable<int> RecieptNo { get; set; }
        public Nullable<decimal> RecptAmt { get; set; }
        public Nullable<System.DateTime> RecptDate { get; set; }
    
        public virtual DemandDetail DemandDetail { get; set; }
        public virtual Form4 Form4 { get; set; }
        public virtual Period Period { get; set; }
    }
}
