//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandLedgerDetail
    {
        public int DemandLedgerDetailsID { get; set; }
        public Nullable<int> DDID { get; set; }
        public Nullable<int> LedgerDetailID { get; set; }
        public string DemandLedgerDetail1 { get; set; }
    
        public virtual DemandDetail DemandDetail { get; set; }
        public virtual LedgerDetail LedgerDetail { get; set; }
    }
}
