//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.DemandDetails = new HashSet<DemandDetail>();
        }
    
        public int DemandID { get; set; }
        public Nullable<int> CitizenID { get; set; }
        public string HouseNo { get; set; }
        public System.DateTime StopDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandDetail> DemandDetails { get; set; }
    }
}
