//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form10Det
    {
        public int Form10DetID { get; set; }
        public Nullable<int> Form10ID { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> SubLedgerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Form10 Form10 { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual SubLedger SubLedger { get; set; }
    }
}
