//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form4()
        {
            this.Corrections = new HashSet<Correction>();
            this.RVdetails = new HashSet<RVdetail>();
            this.DemandYears = new HashSet<DemandYear>();
        }
    
        public int RecieptNo { get; set; }
        public Nullable<int> CitizenID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> SubLedgerID { get; set; }
        public string RecvdFrom { get; set; }
        public string HouseNo { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Correction> Corrections { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual SubLedger SubLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RVdetail> RVdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandYear> DemandYears { get; set; }
    }
}
