//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseTaxCert
    {
        public int HouseTaxCertID { get; set; }
        public string PersonName { get; set; }
        public string WardNo { get; set; }
        public string PersonAddress { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string PrevPersonName { get; set; }
        public Nullable<int> Fees { get; set; }
        public string DeveloperName { get; set; }
        public string DeveloperAddress { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RegisterTypeID { get; set; }
        public Nullable<int> WEBstatusID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
        public virtual WEBstatu WEBstatu { get; set; }
    }
}
