//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllegalConstruction
    {
        public int IllegalConID { get; set; }
        public Nullable<System.DateTime> DateOfComp { get; set; }
        public string NameOfPr { get; set; }
        public string AddressOfPr { get; set; }
        public string NatOfCon { get; set; }
        public string OccasOfCons { get; set; }
        public string ActionTaken { get; set; }
        public string Remarks { get; set; }
        public int RegisterTypeID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
    }
}
