//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvItem()
        {
            this.InOutRegsRecpts = new HashSet<InOutRegsRecpt>();
            this.InOutRegsIssues = new HashSet<InOutRegsIssue>();
        }
    
        public int ItemID { get; set; }
        public string Item { get; set; }
        public int RegisterTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InOutRegsRecpt> InOutRegsRecpts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InOutRegsIssue> InOutRegsIssues { get; set; }
        public virtual RegisterType RegisterType { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
