//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inward
    {
        public int InwardID { get; set; }
        public Nullable<System.DateTime> DateOfReciept { get; set; }
        public string FromWhereRec { get; set; }
        public string NoOfLett { get; set; }
        public Nullable<System.DateTime> DateOfLett { get; set; }
        public string FileNo { get; set; }
        public string SubjectMatter { get; set; }
        public Nullable<System.DateTime> ActionTaken { get; set; }
        public string Remark { get; set; }
        public int RegisterTypeID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
    }
}
