//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public int LeaveBalanceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<int> LeaveYear { get; set; }
        public Nullable<decimal> LeaveDays { get; set; }
        public Nullable<int> Attendance { get; set; }
    }
}
