//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        public int LeaveApplicationID { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string UserID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<System.DateTime> LeaveStartDate { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
    }
}
