//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingID { get; set; }
        public string Subject { get; set; }
        public string ProposerName { get; set; }
        public Nullable<bool> PropOrAmend { get; set; }
        public Nullable<int> For { get; set; }
        public Nullable<int> Against { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string Resolution { get; set; }
        public string Remark { get; set; }
        public int RegisterTypeID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
    }
}
