//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementReg
    {
        public int MovementRegID { get; set; }
        public string NameAndDes { get; set; }
        public Nullable<System.DateTime> TimeOfDeparture { get; set; }
        public Nullable<System.DateTime> TimeOfReturn { get; set; }
        public string PlaceAndPurpose { get; set; }
    }
}
