//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationCertDetail
    {
        public int OccupationCertDetailsID { get; set; }
        public Nullable<int> OccupationCertificateID { get; set; }
        public string FlatNo { get; set; }
        public string HouseNo { get; set; }
        public Nullable<decimal> HouseTax { get; set; }
        public Nullable<decimal> GarbageTax { get; set; }
    
        public virtual OccupationCertificate OccupationCertificate { get; set; }
    }
}
