//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PovertyCertificate
    {
        public int PovertyCertificateID { get; set; }
        public Nullable<int> RegisterTypeID { get; set; }
        public string PersonName { get; set; }
        public string OtherName { get; set; }
        public string PersonAddress { get; set; }
        public string RequestedBy { get; set; }
        public string AddOfPerReqBy { get; set; }
        public string UserID { get; set; }
        public Nullable<int> WEBstatusID { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
        public virtual WEBstatu WEBstatu { get; set; }
    }
}
