//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyBooking
    {
        public int PropertyBookingID { get; set; }
        public int PropertyID { get; set; }
        public string Inward_No { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string NameOfApplicant { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> HDate { get; set; }
        public Nullable<int> AdvReceiptNo { get; set; }
        public Nullable<decimal> AdvAmount { get; set; }
        public Nullable<int> SecurityDepositAmt { get; set; }
        public string ApplForSDRefund { get; set; }
        public Nullable<int> FullPayReceiptNo { get; set; }
        public Nullable<decimal> FullPayAmount { get; set; }
        public Nullable<int> LuxTaxReceiptNo { get; set; }
        public Nullable<int> RefundSDVoucherNo { get; set; }
        public Nullable<decimal> PaymentOfLuxTax { get; set; }
        public string Remarks { get; set; }
    
        public virtual Form4 Form4 { get; set; }
        public virtual Form4 Form41 { get; set; }
        public virtual Form4 Form42 { get; set; }
        public virtual Property Property { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
