//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidenceCertificate
    {
        public int ResidenceCertificateID { get; set; }
        public string PersonName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string NameOfMother { get; set; }
        public string NameOfFather { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<int> Since { get; set; }
        public Nullable<bool> IsDead { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RegisterTypeID { get; set; }
        public Nullable<int> WebStatusID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> TillDate { get; set; }
    
        public virtual RegisterType RegisterType { get; set; }
        public virtual WEBstatu WEBstatu { get; set; }
    }
}
