//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class RVdetail
    {
        public int RVdetailID { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public int LedgerDetailID { get; set; }
        public string RVDetail1 { get; set; }
    
        public virtual Form4 Form4 { get; set; }
        public virtual LedgerDetail LedgerDetail { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
