//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.Corrections = new HashSet<Correction>();
            this.PropertyBookings = new HashSet<PropertyBooking>();
            this.RVdetails = new HashSet<RVdetail>();
        }
    
        public int VoucherID { get; set; }
        public string PassedBy { get; set; }
        public string of { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public string For { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> CBfolio { get; set; }
        public string ResNo { get; set; }
        public Nullable<System.DateTime> HeldOn { get; set; }
        public string Meeting { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> SubLedgerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Correction> Corrections { get; set; }
        public virtual Ledger Ledger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyBooking> PropertyBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RVdetail> RVdetails { get; set; }
        public virtual SubLedger SubLedger { get; set; }
    }
}
