//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherLedgerDetail
    {
        public int VocherLedgerDetailID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<int> LedgerDetailID { get; set; }
        public string VoucherLedgerDetail1 { get; set; }
    
        public virtual LedgerDetail LedgerDetail { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
