//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPRentDetail
    {
        public int VPRentID { get; set; }
        public int Month { get; set; }
        public decimal Arrears { get; set; }
        public decimal Current { get; set; }
        public decimal RecoveryAmt { get; set; }
        public System.DateTime RecoveryDate { get; set; }
        public decimal BalanceArrears { get; set; }
        public decimal BalanceCurrent { get; set; }
    
        public virtual VPRent VPRent { get; set; }
    }
}
