//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panchayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorksID { get; set; }
        public string NameOfWork { get; set; }
        public string TechSanctionNo { get; set; }
        public string ContractorName { get; set; }
        public string PercentageAccepted { get; set; }
        public Nullable<int> EMDIOrecptID { get; set; }
        public Nullable<int> SDIOrecptID { get; set; }
        public Nullable<int> ITrecptNo { get; set; }
        public Nullable<int> RoyaltyDeposit { get; set; }
        public string TimeLimit { get; set; }
        public string ExtentionTime { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> TenderedCost { get; set; }
        public Nullable<decimal> FinalValue { get; set; }
        public Nullable<decimal> NetPaymentToContractor { get; set; }
        public Nullable<System.DateTime> CommenceDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> GrantsRecieved { get; set; }
        public Nullable<decimal> GrantsUtilized { get; set; }
        public string MBNo { get; set; }
    
        public virtual Form4 Form4 { get; set; }
        public virtual Form4 Form41 { get; set; }
        public virtual InOutRegsRecpt InOutRegsRecpt { get; set; }
        public virtual InOutRegsRecpt InOutRegsRecpt1 { get; set; }
    }
}
